### ISSUE TITLE
Review all commands to set/get log levels in IOTAs

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/iotagent-node-lib#1146]
Review all commands to set/get log levels in IOTAs

One attempt to set log level to WARN:
```
curl -X PUT http://host-iota-json:4052/admin/log?level=WARN
{"error":"invalid log level"}
```

Forces to use non standard style:
```
curl -X PUT http://host-iota-json:4052/admin/log?level=WARNING
```

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/1147

**Comment by cesarjorgemartinez** [comment]
The IOTA_LOG_LEVEL variable works correctly.
Testing launching `curl -X PUT http://host-iota-json:4052/admin/log?level=WARNING`:
The logs appeared as DEBUG.

**Comment by AlvaroVega** [comment]
> The IOTA_LOG_LEVEL variable works correctly. Testing launching `curl -X PUT http://host-iota-json:4052/admin/log?level=WARNING`: The logs appeared as DEBUG.

In fact change to WARNING level was not working, since logs were still appearing with previous level

**Comment by cesarjorgemartinez** [comment]
When set WARNING not back into the previous level (was in INFO). Directly changes to DEBUG.
